/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author patev6618
 */
public class Mortgage extends javax.swing.JFrame{

 
    private String mortgagedProperty;
    private Player player1;
    private Screen s;
  
//    private String player1ShowBalance;
//    private Screen s;
    /**
     * Creates new form Mortgage
     */
    public Mortgage() {
        initComponents();
       
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        heading.setText("You can mortgage an owned property");
        instructions.setText("By doing so, you will recieve half of the price of your property from the bank.");
        warning.setText("but will not be able to collect rent from that property");
        questionInput.setText("What property would you like to mortgage?");
    }
  public Mortgage(Player player1) {
        initComponents();
       this.player1 = player1;
      
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        heading.setText("You can mortgage an owned property");
        instructions.setText("By doing so, you will recieve half of the price of your property from the bank.");
        warning.setText("but will not be able to collect rent from that property");
        questionInput.setText("What property would you like to mortgage?");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        questionInput = new javax.swing.JLabel();
        mortgageProperty = new javax.swing.JTextField();
        confirmMortgage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        heading.setText("jLabel1");

        instructions.setText("jLabel1");

        warning.setText("jLabel1");

        questionInput.setText("jLabel1");

        mortgageProperty.setText("Enter Property Name");
        mortgageProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mortgagePropertyActionPerformed(evt);
            }
        });

        confirmMortgage.setText("Mortgage it");
        confirmMortgage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmMortgageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmMortgage)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(instructions)
                                .addComponent(heading)
                                .addComponent(warning)
                                .addComponent(questionInput)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(mortgageProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(heading)
                .addGap(18, 18, 18)
                .addComponent(instructions)
                .addGap(18, 18, 18)
                .addComponent(warning)
                .addGap(44, 44, 44)
                .addComponent(questionInput)
                .addGap(18, 18, 18)
                .addComponent(mortgageProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(confirmMortgage)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mortgagePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mortgagePropertyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mortgagePropertyActionPerformed

    private void confirmMortgageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmMortgageActionPerformed
        // TODO add your handling code here:
     mortgagedProperty = mortgageProperty.getText();

     if (mortgagedProperty.equals(player1.findProperty(mortgagedProperty))){
        player1.mortgage(player1.findPropertyP(mortgagedProperty),player1.findPropertyPrice(mortgagedProperty));
       
    }//GEN-LAST:event_confirmMortgageActionPerformed
     
    }
    public int returnPrice(){
       return player1.getBalance();
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mortgage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmMortgage;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel instructions;
    private javax.swing.JTextField mortgageProperty;
    private javax.swing.JLabel questionInput;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
