/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author patev6618
 */
public class Mortgage extends javax.swing.JFrame{

    //instance variables 
    private String mortgagedProperty;
    private Player player;
  
    /**
     * Creates new form Mortgage
     */
    public Mortgage() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);   
        
    }
    /**
     * create constructor that passes in player class
     * @param player 
     */
  public Mortgage(Player player) {
        initComponents();
       this.player = player;
       this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionInput = new javax.swing.JLabel();
        mortgageProperty = new javax.swing.JTextField();
        confirmMortgage = new javax.swing.JButton();
        takeawayMortgage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));

        questionInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        questionInput.setText("Write the name of the property you would like to mortgage or take out of mortgage");

        mortgageProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mortgagePropertyActionPerformed(evt);
            }
        });

        confirmMortgage.setFont(new java.awt.Font("Roboto Mono", 1, 18)); // NOI18N
        confirmMortgage.setText("Mortgage ");
        confirmMortgage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmMortgageActionPerformed(evt);
            }
        });

        takeawayMortgage.setFont(new java.awt.Font("Roboto Mono", 1, 18)); // NOI18N
        takeawayMortgage.setText("Unmortgage");
        takeawayMortgage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeawayMortgageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Then click the appropriate button to carry out the action ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setText("Enter Property Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(questionInput))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mortgageProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmMortgage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takeawayMortgage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(questionInput)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mortgageProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmMortgage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addComponent(takeawayMortgage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mortgagePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mortgagePropertyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mortgagePropertyActionPerformed

    private void confirmMortgageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmMortgageActionPerformed
        // TODO add your handling code here:
        //if the inputed property name is in the player's list of owned properties
        //carry out mortgaging action
     mortgagedProperty = mortgageProperty.getText();
     if (player.findProperty(mortgagedProperty).equals(mortgagedProperty)){
        player.mortgage(player.findPropertyP(mortgagedProperty),player.findPropertyP(mortgagedProperty).getPrice());
     }else{
         JOptionPane.showMessageDialog(null, "You do not own this property");
     }
     
    }//GEN-LAST:event_confirmMortgageActionPerformed

    private void takeawayMortgageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeawayMortgageActionPerformed
        // TODO add your handling code here:
        //if the inputed property name is in the player's list of owned properties
        //carry out take out of mortgaging action
        mortgagedProperty = mortgageProperty.getText();
        if (player.findProperty(mortgagedProperty).equals(mortgagedProperty)){
        player.removeMortgage(player.findPropertyP(mortgagedProperty),player.findPropertyP(mortgagedProperty).getPrice());
     }else{
         JOptionPane.showMessageDialog(null, "You do not own this property");
     }
        
    }//GEN-LAST:event_takeawayMortgageActionPerformed
     
     
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mortgage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmMortgage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mortgageProperty;
    private javax.swing.JLabel questionInput;
    private javax.swing.JButton takeawayMortgage;
    // End of variables declaration//GEN-END:variables
}
